### ISSUE TITLE
Please leave documentation on how to run your project before code review

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/martha-project-week-6#3]
I would love to have tried out your project, but I can't run it because I'm missing the required token file.

In future projects, please make sure you have some documentation in your repo's readme that explains what your project does, how to install and run it locally, and how to obtain and add any required secrets such as API keys. You might also share the API key or .env file in the Slack channel to help your code reviewers.

**Comment by marthaklambert** [comment]
This has been added now- I left the documentation to do on friday as I was very stretched for time, but in future I will add the important info such as how to run the app straight away. Thanks!

**Comment by arrested-developer** [comment]
I know you were very stretched for time this week! Thanks
